
services:
  # Kafka service
  kafka-0:
    image: bitnami/kafka:3.5
    container_name: kafka_container_microservices_sendmail
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9091,CONTROLLER://:9092,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9091,EXTERNAL://kafka-0:9094
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms512M
      - KAFKA_CFG_LOG_RETENTION_HOURS=168
      - KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./data/kafka_data:/bitnami/kafka
    networks:
      - msendmail-network
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --list --bootstrap-server kafka-0:9091 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kafka UI
  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui_microservices_sendmail
    ports:
      - "8083:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=env-kafka-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-0:9091
    depends_on:
      kafka-0:
        condition: service_healthy
    networks:
      - msendmail-network

  # MSV Sendmail service
  app:
    build: 
        context: .
        dockerfile: Dockerfile
    container_name: crm_msv_sendmail_go
    depends_on:
        kafka-0:
            condition: service_healthy
    networks:
      - msendmail-network

networks:
  msendmail-network:
    driver: bridge
